#!/bin/bash -l

logic_which() {
    which $1 > /dev/null
    return `echo $?`
}
export -f logic_which

os_dep_install() {
    if logic_which yum 
        then
            sudo yum -y update && \
            sudo yum groupinstall -y "Development Tools" && \
            sudo yum install -y curl git irb python-setuptools ruby perl-Digest-SHA java-1.8.0-openjdk-devel
        elif logic_which apt-get
            then
                sudo apt-get update && \
                sudo apt-get install -y build-essential curl git python-setuptools ruby python-software-properties debconf-utils && \
                sudo add-apt-repository -y ppa:webupd8team/java && \
                sudo apt-get update && \
                echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
                sudo apt-get install -y oracle-java8-installer
        else
            echo "Unknown operating system"
    fi
}
export -f os_dep_install


## Install dependencies
os_dep_install
sudo useradd -md /home/jenkinsrc jenkinsrc
sudo su - jenkinsrc
mkdir ~/.ssh
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
cat <<EOT >> ~/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGUlBDq5JXOLu/wdXTHLsVvbswiBYfBtVbxEgbol+VlB6zoy5lbjNkY7n/2YR2QJUjLjU4Z9dziVCIEMhmwZe9hgFsFZIaYIEX0DuJuIN0KRqE0VZlZCmuLgfsX6PjY14tshkBWGRshgYGZnIz2g/YGLxTOE7YNDA6SsF45Df5UEKp/EXul7IBpPz3Fu8D5Xr2aAi0fOTj9pCUSWPBapDD44d00E+JxaEf9PI6xW8SaTcJOtSGNOA5yZcJO2F6vhkZ6rF2JYIrcLU4FxaG90Q0HlAlHDpX5ARtRH1YRNgND2hBCxz4wKeTzJYv2Rx+AVOPjqLeOi8GUwKaebniBfnv jenkins
EOT



## Brew installation
git clone --depth 1 https://github.com/Linuxbrew/brew.git ~/.linuxbrew

cat <<EOT >> ~/.bashrc
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
EOT

## Print IP address of the machine
ip addr list|grep inet